import { z } from "zod";
import { RatingSchema } from "./rating.js";

/**
 * A generic 8-4-4-4-12 hex id, WITHOUT zod's strict RFC-4122 version/
 * variant nibble check. `z.string().uuid()` rejects
 * `00000000-0000-0000-0000-000000000001` (packages/db's `ORG_DEFAULT`
 * seed constant) because its version nibble is `0`, not `1`-`8` — but
 * Postgres's own `uuid` column type doesn't enforce a version either,
 * so rejecting it here would be stricter than the database it
 * describes. Used for `org_id` only; ids actually generated by
 * `gen_random_uuid()` (submission/event ids) are properly-versioned v4
 * and would pass the strict check too, but there's no reason to hold
 * them to a stricter standard than the column they come from.
 */
const UuidLikeSchema = z.string().regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

/**
 * ADR-0017 §5: every event payload carries this envelope. Event-specific
 * schemas extend it with their own fields. `schema_version` is a literal
 * per event (bumped by adding a new `v2` schema, never by mutating `v1`
 * in place) so a consumer can dispatch on it without guessing.
 */
const EventEnvelopeSchema = z.object({
  event_id: z.string().uuid(),
  occurred_at: z.string().datetime(),
  submission_id: z.string().uuid(),
  org_id: UuidLikeSchema,
});

export const SubmissionReceivedEventSchema = EventEnvelopeSchema.extend({
  event_type: z.literal("submission.received"),
  schema_version: z.literal("v1"),
  payload: z.object({
    url: z.string().url().nullable(),
    text: z.string().nullable(),
    submitted_by: z.string().nullable(),
    // ADR-0002/0004 amendment #6: for a third-party video URL we never
    // download audio — the submitter's quote + timestamp ARE the input the
    // pipeline checks. These must travel on the event or the pipeline
    // verifies an empty quote (code-review blocker #2).
    quote: z.string().nullable(),
    timestamp_sec: z.number().int().nonnegative().nullable(),
    // ADR-0032 (two-engine pivot): provenance of this submission.received
    // emission. `.default("submission")` keeps every existing producer
    // (services/api's submission-service.ts, which never sets this field)
    // parsing unchanged — the new value is additive, not a breaking
    // schema change. The fetch engine (services/pipeline's fetch hop) is
    // the only producer that sets "fetch" explicitly.
    ingest_source: z.enum(["submission", "fetch"]).default("submission"),
    // Feed-quality (virality): the raw engagement counts the fetch engine
    // observed for this item at ingestion (youtube_fetch_source.py), and a
    // single pre-computed `virality_score` derived from them in the
    // pipeline (services/pipeline/app/stores/outbox_postgres.py). Both are
    // `.default(null)` so EVERY existing producer parses unchanged — the
    // human-submission path (submission-service.ts) and historical fetch
    // rows never set them, which is exactly "submission-sourced items have
    // none". Only the fetch engine populates them.
    engagement: z
      .object({
        views: z.number().int().nonnegative(),
        likes: z.number().int().nonnegative(),
        comments: z.number().int().nonnegative(),
      })
      .nullable()
      .default(null),
    virality_score: z.number().nonnegative().nullable().default(null),
  }),
});
export type SubmissionReceivedEvent = z.infer<typeof SubmissionReceivedEventSchema>;

export const SubmissionAnalyzedEventSchema = EventEnvelopeSchema.extend({
  event_type: z.literal("submission.analyzed"),
  schema_version: z.literal("v1"),
  payload: z.object({
    claim_count: z.number().int().nonnegative(),
  }),
});
export type SubmissionAnalyzedEvent = z.infer<typeof SubmissionAnalyzedEventSchema>;

export const CheckDraftedEventSchema = EventEnvelopeSchema.extend({
  event_type: z.literal("check.drafted"),
  schema_version: z.literal("v1"),
  payload: z.object({
    check_id: z.string().uuid(),
    rating: RatingSchema.nullable(),
  }),
});
export type CheckDraftedEvent = z.infer<typeof CheckDraftedEventSchema>;

export const CheckFailedEventSchema = EventEnvelopeSchema.extend({
  event_type: z.literal("check.failed"),
  schema_version: z.literal("v1"),
  payload: z.object({
    reason: z.string().min(1).max(2_000),
    retryable: z.boolean(),
  }),
});
export type CheckFailedEvent = z.infer<typeof CheckFailedEventSchema>;

export const CheckPublishedEventSchema = EventEnvelopeSchema.extend({
  event_type: z.literal("check.published"),
  schema_version: z.literal("v1"),
  payload: z.object({
    check_id: z.string().uuid(),
    rating: RatingSchema,
    // ADR-0032 (two-engine pivot) / AT-0032-6: "every published fetched
    // assessment carries ingest_source: 'fetch' provenance". `.default
    // ("submission")` keeps every existing producer (the submission
    // engine's enactment path, which never sets this field) parsing
    // unchanged — additive, not a breaking schema change.
    ingest_source: z.enum(["submission", "fetch"]).default("submission"),
  }),
});
export type CheckPublishedEvent = z.infer<typeof CheckPublishedEventSchema>;

/**
 * ADR-0032 §2 / ADR-0017 amendment AT-0017-C: the three `fetch.*` events
 * the autonomous fetch engine emits alongside (never instead of) the
 * existing `submission.received` conversion. Each carries the same
 * envelope as every other outbox event; `submission_id` is the
 * CANDIDATE's eventual/would-be submission id (ADR-0032 §2: "a surviving
 * novel candidate converts to the existing submission.received.v1"), so a
 * `fetch.candidate` row and the `submission.received` row it produces
 * share one id and can be joined without a second lookup.
 */
export const FetchPollScheduledEventSchema = EventEnvelopeSchema.extend({
  event_type: z.literal("fetch.poll.scheduled"),
  schema_version: z.literal("v1"),
  payload: z.object({
    platform: z.string().min(1),
  }),
});
export type FetchPollScheduledEvent = z.infer<typeof FetchPollScheduledEventSchema>;

export const FetchCandidateEventSchema = EventEnvelopeSchema.extend({
  event_type: z.literal("fetch.candidate"),
  schema_version: z.literal("v1"),
  payload: z.object({
    platform: z.string().min(1),
    source_id: z.string().min(1),
    content_hash: z.string().min(1),
    observed_at: z.string().datetime(),
    engagement_snapshot: z.record(z.string(), z.number()),
    score: z.number(),
  }),
});
export type FetchCandidateEvent = z.infer<typeof FetchCandidateEventSchema>;

export const FetchObservationEventSchema = EventEnvelopeSchema.extend({
  event_type: z.literal("fetch.observation"),
  schema_version: z.literal("v1"),
  payload: z.object({
    platform: z.string().min(1),
    source_id: z.string().min(1),
    content_hash: z.string().min(1),
    observed_at: z.string().datetime(),
    engagement_snapshot: z.record(z.string(), z.number()),
  }),
});
export type FetchObservationEvent = z.infer<typeof FetchObservationEventSchema>;

/**
 * Discriminated union over every known outbox event, keyed on
 * `event_type`. The outbox relay and SSE replay path parse against this
 * so an unrecognised `event_type` in a stored row is a validation error,
 * not a silent `any`.
 */
/**
 * ADR-0025 §6: a correction is always additive, never a rewrite of the
 * prior verdict row (AT-0025-4). `previous_check_id` lets a consumer
 * (apps/web's history view) chain corrections back to the original.
 */
export const CheckCorrectedEventSchema = EventEnvelopeSchema.extend({
  event_type: z.literal("check.corrected"),
  schema_version: z.literal("v1"),
  payload: z.object({
    check_id: z.string().uuid(),
    previous_check_id: z.string().uuid(),
    rating: RatingSchema,
  }),
});
export type CheckCorrectedEvent = z.infer<typeof CheckCorrectedEventSchema>;

export const OutboxEventSchema = z.discriminatedUnion("event_type", [
  SubmissionReceivedEventSchema,
  SubmissionAnalyzedEventSchema,
  CheckDraftedEventSchema,
  CheckFailedEventSchema,
  CheckPublishedEventSchema,
  CheckCorrectedEventSchema,
  FetchPollScheduledEventSchema,
  FetchCandidateEventSchema,
  FetchObservationEventSchema,
]);
export type OutboxEvent = z.infer<typeof OutboxEventSchema>;

export const EVENT_TYPES = [
  "submission.received",
  "submission.analyzed",
  "check.drafted",
  "check.failed",
  "check.published",
  "check.corrected",
  "fetch.poll.scheduled",
  "fetch.candidate",
  "fetch.observation",
] as const;
export type EventType = (typeof EVENT_TYPES)[number];
