# DO NOT EDIT — generated by `pnpm gen:contracts` from packages/core/generated/contracts.schema.json.
# Source of truth: packages/core/src/schemas/*.ts (zod). Re-run `pnpm gen:contracts` to update.

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Annotated
from uuid import UUID

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    RootModel,
)


class PublishedAt(RootModel[AwareDatetime]):
    root: Annotated[
        AwareDatetime,
        Field(
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$'
        ),
    ]


class CalibratedConfidence(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, le=1.0)]


class WhatWouldChangeThis(RootModel[str]):
    root: Annotated[str, Field(max_length=2000, min_length=1)]


class SpanStart(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=9007199254740991)]


class SpanEnd(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=9007199254740991)]


class Attribution(StrEnum):
    unverified = 'unverified'
    confirmed = 'confirmed'
    not_applicable = 'not_applicable'


class ClaimType(StrEnum):
    checkable = 'checkable'
    opinion = 'opinion'
    prediction = 'prediction'
    rhetoric = 'rhetoric'


class CredibilityTier(StrEnum):
    tier1_primary = 'tier1_primary'
    tier2_established_media = 'tier2_established_media'
    tier3_general = 'tier3_general'
    tier4_unverified = 'tier4_unverified'


class Date(RootModel[date_aliased]):
    root: Annotated[
        date_aliased,
        Field(
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))$'
        ),
    ]


class DemonstrationStatus(StrEnum):
    rumoured = 'rumoured'
    announced = 'announced'
    confirmed = 'confirmed'
    ongoing = 'ongoing'
    ended = 'ended'
    cancelled = 'cancelled'


class EvidenceItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source_id: Annotated[
        UUID,
        Field(
            alias='sourceId',
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
        ),
    ]
    quote: Annotated[str, Field(max_length=2000, min_length=1)]


class Rating(StrEnum):
    true = 'True'
    mostly_true = 'MostlyTrue'
    misleading = 'Misleading'
    false = 'False'
    unproven = 'Unproven'
    not_checkable = 'NotCheckable'


class RiskTier(StrEnum):
    a = 'A'
    b = 'B'
    c = 'C'


class Source(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    url: AnyUrl
    title: Annotated[str, Field(min_length=1)]
    publisher: Annotated[str, Field(min_length=1)]
    credibility_tier: Annotated[CredibilityTier, Field(alias='credibilityTier')]
    published_at: Annotated[
        AwareDatetime | None,
        Field(
            alias='publishedAt',
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$',
        ),
    ] = None
    retrieved_at: Annotated[
        AwareDatetime,
        Field(
            alias='retrievedAt',
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$',
        ),
    ]
    excerpt: Annotated[str | None, Field(max_length=2000, min_length=1)] = None


class SubmissionInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: AnyUrl | None = None
    text: Annotated[str | None, Field(max_length=20000, min_length=1)] = None
    quote: Annotated[str | None, Field(max_length=5000, min_length=1)] = None
    timestamp_sec: Annotated[
        int | None, Field(alias='timestampSec', ge=0, le=86400)
    ] = None
    submitted_by: Annotated[
        str | None, Field(alias='submittedBy', max_length=200, min_length=1)
    ] = None


class SubmissionStatus(StrEnum):
    received = 'received'
    analyzing = 'analyzing'
    analyzed = 'analyzed'
    verifying = 'verifying'
    ready = 'ready'
    failed = 'failed'


class Status(StrEnum):
    joined = 'joined'
    already_joined = 'already_joined'


class WaitlistSignupResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status


class WaitlistSource(StrEnum):
    site = 'site'
    web = 'web'


class Claim(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    check_id: Annotated[
        UUID,
        Field(
            alias='checkId',
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
        ),
    ]
    text: Annotated[str, Field(max_length=2000, min_length=1)]
    claim_type: Annotated[ClaimType, Field(alias='claimType')]
    span_start: Annotated[SpanStart | None, Field(alias='spanStart')]
    span_end: Annotated[SpanEnd | None, Field(alias='spanEnd')]
    named_person: Annotated[bool, Field(alias='namedPerson')]
    attribution: Attribution
    created_at: Annotated[
        AwareDatetime,
        Field(
            alias='createdAt',
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$',
        ),
    ]


class Demonstration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    title: Annotated[str, Field(max_length=200, min_length=1)]
    area: Annotated[str, Field(max_length=200, min_length=1)]
    county: Annotated[str, Field(max_length=100, min_length=1)]
    status: DemonstrationStatus
    date: Date | None
    summary: Annotated[str, Field(max_length=2000, min_length=1)]
    source_url: Annotated[AnyUrl | None, Field(alias='sourceUrl')]
    updated_at: Annotated[
        AwareDatetime,
        Field(
            alias='updatedAt',
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$',
        ),
    ]


class Submission(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    url: AnyUrl | None
    text: str | None
    submitted_by: Annotated[str | None, Field(alias='submittedBy')]
    status: SubmissionStatus
    created_at: Annotated[
        AwareDatetime,
        Field(
            alias='createdAt',
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$',
        ),
    ]
    updated_at: Annotated[
        AwareDatetime,
        Field(
            alias='updatedAt',
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$',
        ),
    ]


class WaitlistSignupInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    email: Annotated[
        EmailStr,
        Field(
            max_length=254,
            pattern="^(?:[A-Za-z0-9_'+\\-]+\\.)*[A-Za-z0-9_'+\\-]*[A-Za-z0-9_+-]@(?:[A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
        ),
    ]
    source: WaitlistSource | None = None
    referrer: Annotated[str | None, Field(max_length=500)] = None


class Check(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[
        UUID,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    submission_id: Annotated[
        UUID,
        Field(
            alias='submissionId',
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
        ),
    ]
    summary: Annotated[str, Field(max_length=4000, min_length=1)]
    rating: Rating | None
    claims: list[Claim]
    sources: list[Source]
    is_draft: Annotated[bool, Field(alias='isDraft')]
    reviewed_by: Annotated[str | None, Field(alias='reviewedBy')]
    created_at: Annotated[
        AwareDatetime,
        Field(
            alias='createdAt',
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$',
        ),
    ]
    published_at: Annotated[PublishedAt | None, Field(alias='publishedAt')]
    calibrated_confidence: Annotated[
        CalibratedConfidence | None, Field(alias='calibratedConfidence')
    ]
    what_would_change_this: Annotated[
        WhatWouldChangeThis | None, Field(alias='whatWouldChangeThis')
    ]
    evidence: list[EvidenceItem]
    risk_tier: Annotated[RiskTier | None, Field(alias='riskTier')]
