#!/usr/bin/env bash
# Regenerates every derived contract artifact from packages/core's zod
# schemas (the single source of truth):
#
#   1. packages/core/generated/contracts.schema.json  (JSON Schema, via zod's
#      native z.toJSONSchema — see packages/core/scripts/export-json-schema.ts)
#   2. services/pipeline/app/models/generated.py      (Pydantic v2 models,
#      via datamodel-code-generator)
#
# Run via `pnpm gen:contracts` at the repo root. CI runs this same script
# and then `git diff --exit-code` as a drift gate: if either generated file
# doesn't match what's checked in, someone edited a zod schema (or the
# generated files by hand) without regenerating.
#
# Python generation needs services/pipeline's uv-managed virtualenv
# (datamodel-code-generator is a `uv add --dev` dependency there, not a
# root/pnpm dependency) — `uv sync` is idempotent, so running it here keeps
# this script a true single entrypoint rather than assuming the caller
# already did it.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "==> [1/2] packages/core: exporting zod schemas to JSON Schema"
# Called directly (not via `moon run core:gen-schema`) because this script
# is itself invoked BY the `core:gen-contracts` moon task -- a nested moon
# invocation from inside a moon-run action is unsupported/reentrant.
pnpm --filter @fact-checker-ke/core run gen:schema

echo "==> [2/2] services/pipeline: generating Pydantic v2 models"
(
  cd "$REPO_ROOT/services/pipeline"
  uv sync --quiet
  rm -f app/models/generated.py
  uv run datamodel-codegen \
    --input "$REPO_ROOT/packages/core/generated/contracts.schema.json" \
    --input-file-type jsonschema \
    --output app/models/generated.py \
    --output-model-type pydantic_v2.BaseModel \
    --use-subclass-enum \
    --use-annotated \
    --use-default \
    --target-python-version 3.12 \
    --snake-case-field \
    --use-schema-description \
    --disable-timestamp \
    --skip-root-model \
    --custom-file-header "# DO NOT EDIT — generated by \`pnpm gen:contracts\` from packages/core/generated/contracts.schema.json.
# Source of truth: packages/core/src/schemas/*.ts (zod). Re-run \`pnpm gen:contracts\` to update."
)

echo "==> Done. Review with: git diff packages/core/generated services/pipeline/app/models/generated.py"
